### PR TITLE
Fix: Missing linux application_stack input vars

### LINKED ISSUE #31: [AVM Module Issue]: Missing application_stack input vars
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.1

### (Optional) Correlation Id

_No response_

### Description

application_stack Input variables for Linux webapp are missing.

```
This object does not have an attribute named "go_version"
This object does not have an attribute named "java_server".
This object does not have an attribute named "java_server_version".
This object does not have an attribute named "php_version".
This object does not have an attribute named "ruby_version".
```

### PR DESCRIPTION
**Pull request by jamie-oconnell**
## Description
Fixes #31 

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by jamie-oconnell** [comment]
@microsoft-github-policy-service agree

**Comment by donovm4** [comment]
@jamie-oconnell - would like to know your thoughts on the following...

It seems like the AVM team has updated some checks for linting test, so I will fix those errors. I can let you know when those fixes are pushed to main, then we can see if you can pull those new changes and just recommit for these fixes to go through.

**Comment by donovm4** [comment]
@jamie-oconnell - about to push those linting fixes to main branch. I will check on this PR again periodically to see if there are anymore changes to make on my side

**Comment by jamie-oconnell** [comment]
Great stuff thanks @donovm4. Can we please re-run the checks for this PR?

**Pull request merged**
